bind 127.0.0.1
protected-mode yes
port 6379
timeout 0
tcp-keepalive 300

dir __VALKEY_SERVER_DB_DIR__
pidfile __VALKEY_SERVER_PID_FILE__
logfile __VALKEY_SERVER_LOG_FILE__
loglevel notice

daemonize no
databases 16

save 900 1
save 300 10
save 60 10000

appendonly yes
appendfilename appendonly.aof
appendfsync everysec
